const DB_NAME='permitSorterDB', STORE='students', DB_VERSION=1; let students=[], recognition=null, listening=false, deferredInstall=null;
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const demo=[['1001','أحمد محمد علي','كهرباء'],['1002','محمد أحمد حسن','تبريد وتكييف'],['1003','محمود علي إبراهيم','ميكانيكا'],['1004','عبد الرحمن محمد سالم','تركيبات كهربائية'],['1005','يوسف خالد محمود','كهرباء'],['1006','عمر أحمد السيد','ميكانيكا'],['1007','سيف محمد حسن','تبريد وتكييف'],['1008','إسلام محمود علي','تركيبات كهربائية'],['1009','أحمد محمود إبراهيم','كهرباء'],['1010','محمود محمد عبد الله','ميكانيكا'],['1011','مصطفى أحمد علي','تبريد وتكييف'],['1012','حسن إبراهيم محمد','كهرباء'],['1013','علي محمد حسن','تركيبات كهربائية'],['1014','زياد محمود أحمد','ميكانيكا'],['1015','كريم أحمد سالم','كهرباء'],['1016','عبد الله محمد علي','تبريد وتكييف'],['1017','يوسف محمود حسن','تركيبات كهربائية'],['1018','خالد إبراهيم علي','ميكانيكا'],['1019','محمد علي محمود','كهرباء'],['1020','سيف أحمد إبراهيم','تبريد وتكييف']].map(x=>({id:x[0],name:x[1],major:x[2],sorted:false,sortedAt:null}));
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveAll(arr){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);s.clear();arr.forEach(x=>s.put(x));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function loadAll(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function normalize(s){return String(s??'').toLowerCase().trim().replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/\s+/g,'')}
function score(a,b){a=normalize(a);b=normalize(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .9;const m=a.length,n=b.length,dp=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)dp[i][0]=i;for(let j=0;j<=n;j++)dp[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return 1-dp[m][n]/Math.max(m,n)}
function search(q){return students.map(s=>({...s,score:score(s.name,q)})).filter(s=>s.score>=.42).sort((a,b)=>b.score-a.score).slice(0,7)}
function renderStats(){const total=students.length,done=students.filter(s=>s.sorted).length;$('#totalCount').textContent=total;$('#sortedCount').textContent=done;$('#remainingCount').textContent=total-done;renderSpecs()}
function renderSpecs(){const map={};students.forEach(s=>{map[s.major]??={total:0,done:0};map[s.major].total++;if(s.sorted)map[s.major].done++});$('#specializationList').innerHTML=Object.entries(map).map(([k,v])=>{const p=v.total?Math.round(v.done/v.total*100):0;return `<div class="spec-row"><div class="spec-line"><b>${esc(k)}</b><span>${v.done} / ${v.total} • ${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')||'<div style="text-align:center;color:#718096;font-size:11px;padding:20px">استورد بيانات الطلاب للبدء</div>'}
function renderResults(list){const box=$('#results');if(!list.length){box.innerHTML='<div style="padding:18px;text-align:center;color:#718096;font-size:11px">لم يتم العثور على طالب مطابق.</div>';return}box.innerHTML=list.map((s,i)=>`<div class="student-card" data-id="${esc(s.id)}"><div class="student-top"><div class="avatar">${esc(s.name.trim()[0]||'ط')}</div><div><div class="student-name">${esc(s.name)}</div><div class="student-id">رقم الطالب: ${esc(s.id)}</div></div></div>${s.sorted?'<div class="warning">⚠️ تم فرز تصريح هذا الطالب بالفعل.</div>':''}<div class="major"><small>التخصص</small><b>${esc(s.major)}</b></div><button class="sort-btn ${s.sorted?'done':''}" onclick="toggleSorted('${esc(s.id)}')">${s.sorted?'✓ تم الفرز':'✓ تم فرز التصريح'}</button></div>`).join('')}
window.toggleSorted=async id=>{const s=students.find(x=>String(x.id)===String(id));if(!s)return;s.sorted=!s.sorted;s.sortedAt=s.sorted?new Date().toISOString():null;await saveAll(students);renderStats();renderResults(search($('#searchInput').value));toast(s.sorted?'تم تسجيل فرز التصريح ✓':'تم إلغاء حالة الفرز')};
function doSearch(q){q=q.trim();if(!q){$('#results').innerHTML='';return}$('#searchStatus').textContent='جاري البحث...';const r=search(q);renderResults(r);$('#searchStatus').textContent=r.length?`تم العثور على ${r.length} نتيجة`:'لم يتم العثور على نتيجة'}
let timer;$('#searchInput').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>doSearch(e.target.value),120)});$('#clearSearch').onclick=()=>{$('#searchInput').value='';$('#results').innerHTML='';$('#searchStatus').textContent='جاهز للبحث';$('#searchInput').focus()};
function setupSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#voiceBtn').onclick=()=>toast('البحث الصوتي غير مدعوم هنا، استخدم البحث الكتابي');return}recognition=new SR();recognition.lang='ar-EG';recognition.interimResults=false;recognition.maxAlternatives=4;recognition.onstart=()=>{listening=true;$('#voiceBtn').classList.add('listening');$('#searchStatus').textContent='أنا أستمع...';$('#voiceBtn strong').textContent='تحدث الآن'};recognition.onresult=e=>{const text=[...e.results[0]].map(x=>x.transcript).join(' ');$('#searchInput').value=text;doSearch(text)};recognition.onerror=e=>{toast(e.error==='not-allowed'?'اسمح بالوصول للميكروفون من إعدادات المتصفح':'تعذر التقاط الصوت، حاول مرة أخرى');};recognition.onend=()=>{listening=false;$('#voiceBtn').classList.remove('listening');$('#voiceBtn strong').textContent='اضغط وتحدث';if(!$('#searchInput').value)$('#searchStatus').textContent='جاهز للبحث')};$('#voiceBtn').onclick=()=>{if(listening){recognition.stop();return}try{recognition.start()}catch{}}}
$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=handleFile;async function handleFile(e){const f=e.target.files[0];if(!f)return;if(!window.XLSX){toast('مكتبة Excel لم تُحمّل بعد');return}try{const data=await f.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!rows.length)throw Error('empty');const keys=Object.keys(rows[0]);const pick=(names)=>keys.find(k=>names.some(n=>normalize(k).includes(normalize(n))));const idK=pick(['رقم الطالب','رقم','student id','id']),nameK=pick(['اسم الطالب','الاسم','student name','name']),majorK=pick(['التخصص','القسم','التخصص الدراسي','major','specialization']);if(!idK||!nameK||!majorK){toast('لم أجد الأعمدة المطلوبة: رقم الطالب، اسم الطالب، التخصص');return}const arr=rows.map(r=>({id:String(r[idK]).trim(),name:String(r[nameK]).trim(),major:String(r[majorK]).trim(),sorted:false,sortedAt:null})).filter(x=>x.id&&x.name&&x.major);await saveAll(arr);students=arr;renderStats();$('#results').innerHTML='';toast(`تم استيراد ${arr.length} طالب بنجاح ✓`)}catch(err){toast('تعذر قراءة ملف Excel')}}
$('#demoBtn').onclick=async()=>{await saveAll(demo);students=JSON.parse(JSON.stringify(demo));renderStats();toast('تم تحميل بيانات تجريبية ✓')};
$$('.nav-item').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));if(v==='students')showStudents();else if(v==='settings')showSettings();else window.scrollTo({top:0,behavior:'smooth'})});
function showStudents(){const content=`<h2 style="margin:0">كل الطلاب</h2><p style="color:#718096;font-size:11px">${students.length} طالب • ابحث أو راجع حالة الفرز</p><input id="modalSearch" class="search-wrap" style="width:100%;font-family:inherit;padding:0 12px" placeholder="ابحث بالاسم أو الرقم..."> <div id="modalList" class="student-list"></div>`;openModal(content);const render=()=>{const q=normalize($('#modalSearch').value);const arr=students.filter(s=>!q||normalize(s.name).includes(q)||normalize(s.id).includes(q));$('#modalList').innerHTML=arr.slice(0,100).map(s=>`<div class="list-item"><div><b>${esc(s.name)}</b><small>${esc(s.id)} • ${esc(s.major)}</small></div><span class="pill ${s.sorted?'done':''}">${s.sorted?'تم الفرز':'متبقي'}</span></div>`).join('')||'<div style="text-align:center;color:#718096;font-size:11px">لا توجد نتائج</div>'};$('#modalSearch').oninput=render;render()}
function showSettings(){openModal(`<h2 style="margin:0">الإعدادات والبيانات</h2><p style="color:#718096;font-size:11px">بيانات الطلاب محفوظة محليًا على هذا الجهاز.</p><div class="student-list"><button class="action-card" style="width:100%" onclick="document.querySelector('#fileInput').click()"><span>📥</span><div><b>استيراد ملف جديد</b><small>استبدال قاعدة البيانات الحالية</small></div></button><button class="action-card" style="width:100%" onclick="exportCSV()"><span>📤</span><div><b>تصدير النتائج</b><small>تحميل ملف CSV متوافق مع Excel</small></div></button><button class="action-card" style="width:100%" onclick="clearData()"><span>🗑️</span><div><b>مسح جميع البيانات</b><small>لا يمكن التراجع عن هذا الإجراء</small></div></button></div>`)}
window.exportCSV=()=>{const rows=[['رقم الطالب','اسم الطالب','التخصص','الحالة','تاريخ الفرز'],...students.map(s=>[s.id,s.name,s.major,s.sorted?'تم الفرز':'متبقي',s.sortedAt?new Date(s.sortedAt).toLocaleString('ar-EG'):''])];const csv='\\uFEFF'+rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='student-permits-results.csv';a.click();toast('تم تجهيز ملف النتائج ✓')};
window.clearData=async()=>{if(!confirm('هل تريد مسح جميع بيانات الطلاب؟'))return;await saveAll([]);students=[];renderStats();closeModal();toast('تم مسح البيانات')};
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();deferredInstall=null};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
(async()=>{students=await loadAll();renderStats();setupSpeech()})();
